# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ty-sa32o95M02NWtO15Fhvsyl3v9YiV8
"""

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib
from sklearn.datasets import load_iris

# Load model dan data
model = joblib.load("random_forest_iris_model")
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["target"] = iris.target
df["species"] = df["target"].map(dict(enumerate(iris.target_names)))

# Konfigurasi halaman
st.set_page_config(page_title="Iris Classifier", layout="centered")
st.title("🌸 Iris Classification App - All in One")

# Pilihan halaman
menu = st.radio("Pilih Halaman:", ["📊 Deskripsi Data", "🔮 Prediksi", "📈 Visualisasi Data"])

# Halaman 1: Deskripsi Data
if menu == "📊 Deskripsi Data":
    st.header("📊 Deskripsi Dataset Iris")
    st.write("Dataset Iris adalah dataset klasik dalam machine learning.")
    st.dataframe(df)
    st.subheader("Fitur:")
    st.write(iris.feature_names)
    st.subheader("Kelas Target:")
    st.write(iris.target_names)

# Halaman 2: Prediksi
elif menu == "🔮 Prediksi":
    st.header("🔮 Prediksi Spesies Bunga Iris")
    st.write("Masukkan nilai-nilai fitur di bawah ini:")

    # Input user
    sepal_length = st.slider("Sepal Length (cm)", 4.0, 8.0, 5.1)
    sepal_width = st.slider("Sepal Width (cm)", 2.0, 4.5, 3.5)
    petal_length = st.slider("Petal Length (cm)", 1.0, 7.0, 1.4)
    petal_width = st.slider("Petal Width (cm)", 0.1, 2.5, 0.2)

    # Prediksi
    if st.button("Prediksi"):
        input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
        prediction = model.predict(input_data)[0]
        species_name = iris.target_names[prediction]
        st.success(f"🌼 Spesies yang diprediksi: **{species_name}**")

# Halaman 3: Visualisasi
elif menu == "📈 Visualisasi Data":
    st.header("📈 Visualisasi Data Iris")

    plot_type = st.selectbox("Pilih jenis plot:", ["Pairplot", "Heatmap Korelasi"])

   if plot_type == "Pairplot":
    st.write("### Pairplot berdasarkan Spesies")
    pairplot_fig = sns.pairplot(df, hue="species")
    st.pyplot(pairplot_fig.figure)
       
    elif plot_type == "Heatmap Korelasi":
        st.write("### Korelasi antara fitur")
        fig, ax = plt.subplots()
        sns.heatmap(df.iloc[:, :4].corr(), annot=True, cmap="coolwarm", ax=ax)
        st.pyplot(fig)
